server:
  port: 8080
  ajp:
    port: 8009
  use-forward-headers: true
  compression:
    enabled: true
    mime-types: text/html, text/css, application/json
  servlet:
    context-path: /test

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.example: DEBUG
  file: app.log

spring:
  jackson:
    mapper:
      default_view_inclusion: true
    serialization:
      indent_output: true
      write_dates_as_timestamps: true
    deserialization:
      fail_on_ignored_properties: false
      fail_on_unknown_properties: false
      accept_single_value_as_array: true
    default-property-inclusion: non_empty

  datasource:
    url: jdbc:mariadb://localhost:3306/testdb
    username: root
    password: root
    #cachePrepStmts: true
    #prepStmtCacheSize: 250
    #prepStmtCacheSqlLimit: 2048
    #useServerPrepStmts: true

  jpa:
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      # fixes Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
      hibernate.jdbc.lob.non_contextual_creation: true

  data:
    jpa:
      repositories.enabled: true
